### ISSUE TITLE
incorrect lookup of image grub path

### ISSUE THREAD

**Issue by gdstewart** [OSInside/kiwi#1754]
## Problem description
I tried to build an ISO image for Debian 10 and it failed with this error. I tried again with the [example appliance description for Debian 10](https://github.com/OSInside/kiwi-descriptions/tree/master/debian/x86_64/debian-buster) and it failed with the same error.

```
graeme@graeme:~> sudo kiwi-ng --profile=Disk --type oem system build --description kiwi-descriptions/debian/x86_64/debian-buster --target-dir /var/cache/test-image-debian
[ INFO    ]: 16:31:43 | Reading runtime config file: '/etc/kiwi.yml'
[ INFO    ]: 16:31:43 | Loading XML description
[ INFO    ]: 16:31:43 | Support for XML markup available
[ INFO    ]: 16:31:43 | --> loaded kiwi-descriptions/debian/x86_64/debian-buster/config.xml
[ INFO    ]: 16:31:43 | --> Selected build type: oem
[ INFO    ]: 16:31:43 | --> Selected profiles: Disk
[ INFO    ]: 16:31:43 | Preparing new root system
[ INFO    ]: 16:31:43 | Setup root directory: /var/cache/test-image-debian/build/image-root
[ INFO    ]: 16:31:43 | Setting up repository http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 16:31:43 | --> Type: apt-deb
[ INFO    ]: 16:31:43 | --> Translated: http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 16:31:43 | --> Alias: 11d73968d25aec7118b11e0a8762028d
[ INFO    ]: 16:31:43 | Setting up repository obs://Virtualization:Appliances:Builder/Debian_10
[ INFO    ]: 16:31:43 | --> Type: apt-deb
[ INFO    ]: 16:31:44 | --> Translated: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/Debian_10/
[ INFO    ]: 16:31:44 | --> Alias: 80d9781543808931573b34b958c155e3
[ INFO    ]: 16:31:44 | Using package manager backend: apt-get
[ INFO    ]: 16:31:44 | Installing bootstrap packages
[ INFO    ]: 16:31:44 | --> collection type: onlyRequired
[ INFO    ]: 16:31:44 | --> package: apt-get
[ INFO    ]: 16:31:44 | --> package: grub2
[ INFO    ]: 16:31:44 | --> package: usrmerge
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 16:33:47 | Installing system (chroot) for build type: oem
[ INFO    ]: 16:33:47 | --> collection type: onlyRequired
[ INFO    ]: 16:33:47 | --> package: binutils
[ INFO    ]: 16:33:47 | --> package: bsdmainutils
[ INFO    ]: 16:33:47 | --> package: dracut
[ INFO    ]: 16:33:47 | --> package: dracut-kiwi-oem-dump
[ INFO    ]: 16:33:47 | --> package: dracut-kiwi-oem-repart
[ INFO    ]: 16:33:47 | --> package: gnupg
[ INFO    ]: 16:33:47 | --> package: grub-efi-amd64
[ INFO    ]: 16:33:47 | --> package: grub-theme-starfield
[ INFO    ]: 16:33:47 | --> package: ifupdown
[ INFO    ]: 16:33:47 | --> package: init
[ INFO    ]: 16:33:47 | --> package: iproute2
[ INFO    ]: 16:33:47 | --> package: iptables
[ INFO    ]: 16:33:47 | --> package: iputils-ping
[ INFO    ]: 16:33:47 | --> package: isc-dhcp-client
[ INFO    ]: 16:33:47 | --> package: isolinux
[ INFO    ]: 16:33:47 | --> package: linux-image-amd64
[ INFO    ]: 16:33:47 | --> package: netbase
[ INFO    ]: 16:33:47 | --> package: plymouth
[ INFO    ]: 16:33:47 | --> package: plymouth-themes
[ INFO    ]: 16:33:47 | --> package: syslinux
[ INFO    ]: 16:33:47 | --> package: syslinux-common
[ INFO    ]: 16:33:47 | --> package: vim
[ INFO    ]: 16:33:47 | --> package: xz-utils
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 16:37:08 | Importing Image description to system tree
[ INFO    ]: 16:37:08 | --> Importing state XML description to /var/cache/test-image-debian/build/image-root/image/config.xml
[ INFO    ]: 16:37:08 | --> Importing config.sh script to /var/cache/test-image-debian/build/image-root/image/config.sh
[ INFO    ]: 16:37:08 | --> Importing script helper functions
[ INFO    ]: 16:37:08 | Copying user defined files to image tree
[ INFO    ]: 16:37:08 | Setting up user root
[ INFO    ]: 16:37:08 | --> Modifying user: root
[ INFO    ]: 16:37:08 | --> Primary group for user root: root
[ INFO    ]: 16:37:08 | Setting up keytable: us
[ WARNING ]: 16:37:08 | Could not parse systemd-firstboot output
[ WARNING ]: 16:37:08 | keyboard setup skipped no capable systemd-firstboot or etc/sysconfig/keyboard found
[ INFO    ]: 16:37:08 | Setting up locale: en_US
[ WARNING ]: 16:37:08 | Could not parse systemd-firstboot output
[ INFO    ]: 16:37:08 | Setting up timezone: Europe/Berlin
[ WARNING ]: 16:37:08 | Could not parse systemd-firstboot output
[ WARNING ]: 16:37:08 | chkstat not found in image. File Permissions Check skipped
[ INFO    ]: 16:37:08 | Calling config.sh script
[ INFO    ]: 16:37:08 | Using package manager backend: apt-get
[ INFO    ]: 16:37:08 | Cleaning up SystemPrepare instance
[ INFO    ]: 16:37:08 | Creating system image
[ INFO    ]: 16:37:08 | Preparing boot system
[ INFO    ]: 16:37:08 | Precalculating required disk size
[ INFO    ]: 16:37:08 | --> system data with filesystem overhead needs 1196 MB
[ INFO    ]: 16:37:08 | --> swap partition adding 128 MB
[ INFO    ]: 16:37:08 | --> legacy bios boot partition adding 2 MB
[ INFO    ]: 16:37:08 | --> EFI partition adding 20 MB
[ INFO    ]: 16:37:08 | Using calculated disk size: 1346 MB
[ INFO    ]: 16:37:08 | Creating raw disk image /var/cache/test-image-debian/Debian-Buster_appliance.x86_64-10.4.raw
[ INFO    ]: 16:37:10 | --> creating EFI CSM(legacy bios) partition
[ INFO    ]: 16:37:12 | --> creating EFI partition
[ INFO    ]: 16:37:14 | --> creating SWAP partition
[ INFO    ]: 16:37:17 | --> creating root partition
[ INFO    ]: 16:37:19 | Creating EFI(fat16) filesystem on /dev/mapper/loop0p2
[ INFO    ]: 16:37:19 | Creating root(ext4) filesystem on /dev/mapper/loop0p4
[ INFO    ]: 16:37:19 | Creating config.partids in boot system
[ INFO    ]: 16:37:19 | Export modprobe configuration
[ INFO    ]: 16:37:19 | Creating image identifier: 0xb16b99f3
[ INFO    ]: 16:37:19 | Creating generic system etc/fstab
[ INFO    ]: 16:37:19 | Creating generic dracut initrd archive
[ INFO    ]: 16:37:45 | --> initrd archive as initrd.img-4.19.0-14-amd64
[ INFO    ]: 16:37:45 | Creating grub2 bootloader configuration
[ INFO    ]: 16:37:45 | Creating grub2 bootloader images
[ INFO    ]: 16:37:45 | --> Creating unsigned efi image
[ INFO    ]: 16:37:45 | Writing grub2 defaults file
[ INFO    ]: 16:37:45 | --> GRUB_GFXMODE:auto
[ INFO    ]: 16:37:45 | --> GRUB_TERMINAL:"gfxterm"
[ INFO    ]: 16:37:45 | --> GRUB_THEME:/boot/grub/themes/starfield/theme.txt
[ INFO    ]: 16:37:45 | --> GRUB_TIMEOUT:10
[ INFO    ]: 16:37:45 | Writing sysconfig bootloader file
[ INFO    ]: 16:37:45 | --> DEFAULT_APPEND:"root=UUID=58799b25-817b-4979-9d13-2a5bc70bd75e rw "
[ INFO    ]: 16:37:45 | --> FAILSAFE_APPEND:"root=UUID=58799b25-817b-4979-9d13-2a5bc70bd75e rw  ide=nodma apm=off noresume edd=off nomodeset 3 "
[ INFO    ]: 16:37:45 | --> LOADER_LOCATION:none
[ INFO    ]: 16:37:45 | --> LOADER_TYPE:grub2-efi
[ INFO    ]: 16:37:45 | Creating config.bootoptions
[ INFO    ]: 16:37:45 | Syncing system to image
[ INFO    ]: 16:37:45 | --> Syncing EFI boot data to EFI partition
[ WARNING ]: 16:37:45 | Extended attributes not supported for target: /tmp/kiwi_mount_manager.doabxlrd
[ INFO    ]: 16:37:45 | --> Syncing root filesystem data
[ INFO    ]: 16:37:49 | Copying /var/cache/test-image-debian/build/image-root/boot/efi/EFI/BOOT/earlyboot.cfg -> /tmp/kiwi_mount_manager.ed0uzrvy/boot/efi/EFI/BOOT/grub.cfg to be found by EFI
[ INFO    ]: 16:37:49 | Cleaning up BootLoaderConfigGrub2 instance
[ INFO    ]: 16:37:49 | Installing grub2 on disk /dev/loop0
[ INFO    ]: 16:37:50 | Cleaning up BootLoaderInstallGrub2 instance
[ INFO    ]: 16:37:50 | Saving boot image instance to file
[ INFO    ]: 16:37:50 | Export deb packages metadata
[ INFO    ]: 16:37:50 | Export deb packages changelog metadata
[ INFO    ]: 16:37:52 | Export deb verification metadata
[ INFO    ]: 16:37:54 | Cleaning up FileSystemSwap instance
[ INFO    ]: 16:37:54 | Cleaning up FileSystemExt4 instance
[ INFO    ]: 16:37:54 | umount FileSystemExt4 instance
[ INFO    ]: 16:37:54 | Cleaning up FileSystemFat16 instance
[ INFO    ]: 16:37:54 | umount FileSystemFat16 instance
[ INFO    ]: 16:37:54 | Cleaning up Disk instance
[ INFO    ]: 16:37:54 | Cleaning up LoopDevice instance
[ INFO    ]: 16:37:54 | Creating hybrid ISO installation image
[ INFO    ]: 16:37:54 | Creating disk image checksum
[ INFO    ]: 16:37:57 | Creating squashfs embedded disk image
[ INFO    ]: 16:38:53 | Setting up install image bootloader configuration
[ INFO    ]: 16:38:53 | Creating grub2 bootloader images
[ INFO    ]: 16:38:53 | --> Creating identifier file 0x3ffd56ee
[ INFO    ]: 16:38:53 | --> Creating bios image
[ ERROR   ]: 16:38:53 | KiwiCommandError: chroot: stderr: grub-mkimage: error: cannot open `/usr/share/grub2/i386-pc/core.img': No such file or directory.
, stdout: (no output on stdout)
[ INFO    ]: 16:38:53 | Cleaning up FileSystemSquashFs instance
[ INFO    ]: 16:38:53 | Cleaning up BootLoaderConfigGrub2 instance
[ INFO    ]: 16:38:53 | Cleaning up InstallImageBuilder instance
```

## Expected behaviour
Successful build for Debian 10.

## Steps to reproduce the behaviour
```
sudo kiwi-ng --profile=Disk --type oem system build --description kiwi-descriptions/debian/x86_64/debian-buster --target-dir /var/cache/debian-buster
```

## OS and Software information
+ KIWI version: 9.23.16
+ Operating system: openSUSE Tumbleweed
+ OBS version: N/A

**Comment by t-ru** [comment]
Correct build command

`kiwi-ng --profile=Disk system build --description kiwi-descriptions/debian/x86_64/debian-buster --target-dir /var/cache/debian-buster`

... if you use "--profile"  do not use  "--type".

You are one Tumbleweed with latest ext4 features. Please try.

```
<type 
   image="oem" 
   filesystem="ext4" 
   initrd_system="dracut" 
   firmware="efi" 
   installiso="true" 
   fscreateoptions="-O ^metadata_csum">
```

**Comment by gdstewart** [comment]
@t-ru I ran the command you provided and it still gave the same error. 

```
graeme@graeme:~> sudo kiwi-ng --profile=Disk system build --description kiwi-descriptions/debian/x86_64/debian-buster --target-dir /var/cache/debian-buster
[sudo] password for root:
[ INFO    ]: 09:02:45 | Reading runtime config file: '/etc/kiwi.yml'
[ INFO    ]: 09:02:45 | Loading XML description
[ INFO    ]: 09:02:45 | Support for XML markup available
[ INFO    ]: 09:02:46 | --> loaded kiwi-descriptions/debian/x86_64/debian-buster/config.xml
[ INFO    ]: 09:02:46 | --> Selected build type: oem
[ INFO    ]: 09:02:46 | --> Selected profiles: Disk
[ INFO    ]: 09:02:46 | Preparing new root system
[ INFO    ]: 09:02:46 | Setup root directory: /var/cache/debian-buster/build/image-root
[ INFO    ]: 09:02:46 | Setting up repository http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 09:02:46 | --> Type: apt-deb
[ INFO    ]: 09:02:46 | --> Translated: http://ftp.halifax.rwth-aachen.de/debian
[ INFO    ]: 09:02:46 | --> Alias: 11d73968d25aec7118b11e0a8762028d
[ INFO    ]: 09:02:46 | Setting up repository obs://Virtualization:Appliances:Builder/Debian_10
[ INFO    ]: 09:02:46 | --> Type: apt-deb
[ INFO    ]: 09:03:53 | --> Translated: http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/Debian_10/
[ INFO    ]: 09:03:53 | --> Alias: 80d9781543808931573b34b958c155e3
[ INFO    ]: 09:03:53 | Using package manager backend: apt-get
[ INFO    ]: 09:03:53 | Installing bootstrap packages
[ INFO    ]: 09:03:53 | --> collection type: onlyRequired
[ INFO    ]: 09:03:53 | --> package: apt-get
[ INFO    ]: 09:03:53 | --> package: grub2
[ INFO    ]: 09:03:53 | --> package: usrmerge
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 09:05:52 | Installing system (chroot) for build type: oem
[ INFO    ]: 09:05:52 | --> collection type: onlyRequired
[ INFO    ]: 09:05:52 | --> package: binutils
[ INFO    ]: 09:05:52 | --> package: bsdmainutils
[ INFO    ]: 09:05:52 | --> package: dracut
[ INFO    ]: 09:05:52 | --> package: dracut-kiwi-oem-dump
[ INFO    ]: 09:05:52 | --> package: dracut-kiwi-oem-repart
[ INFO    ]: 09:05:52 | --> package: gnupg
[ INFO    ]: 09:05:52 | --> package: grub-efi-amd64
[ INFO    ]: 09:05:52 | --> package: grub-theme-starfield
[ INFO    ]: 09:05:52 | --> package: ifupdown
[ INFO    ]: 09:05:52 | --> package: init
[ INFO    ]: 09:05:52 | --> package: iproute2
[ INFO    ]: 09:05:52 | --> package: iptables
[ INFO    ]: 09:05:52 | --> package: iputils-ping
[ INFO    ]: 09:05:52 | --> package: isc-dhcp-client
[ INFO    ]: 09:05:52 | --> package: isolinux
[ INFO    ]: 09:05:52 | --> package: linux-image-amd64
[ INFO    ]: 09:05:52 | --> package: netbase
[ INFO    ]: 09:05:52 | --> package: plymouth
[ INFO    ]: 09:05:52 | --> package: plymouth-themes
[ INFO    ]: 09:05:52 | --> package: syslinux
[ INFO    ]: 09:05:52 | --> package: syslinux-common
[ INFO    ]: 09:05:52 | --> package: vim
[ INFO    ]: 09:05:52 | --> package: xz-utils
[ INFO    ]: Processing: [########################################] 100%
[ INFO    ]: 09:09:11 | Importing Image description to system tree
[ INFO    ]: 09:09:11 | --> Importing state XML description to /var/cache/debian-buster/build/image-root/image/config.xml
[ INFO    ]: 09:09:11 | --> Importing config.sh script to /var/cache/debian-buster/build/image-root/image/config.sh
[ INFO    ]: 09:09:11 | --> Importing script helper functions
[ INFO    ]: 09:09:11 | Copying user defined files to image tree
[ INFO    ]: 09:09:11 | Setting up user root
[ INFO    ]: 09:09:11 | --> Modifying user: root
[ INFO    ]: 09:09:11 | --> Primary group for user root: root
[ INFO    ]: 09:09:11 | Setting up keytable: us
[ WARNING ]: 09:09:11 | Could not parse systemd-firstboot output
[ WARNING ]: 09:09:11 | keyboard setup skipped no capable systemd-firstboot or etc/sysconfig/keyboard found
[ INFO    ]: 09:09:11 | Setting up locale: en_US
[ WARNING ]: 09:09:11 | Could not parse systemd-firstboot output
[ INFO    ]: 09:09:11 | Setting up timezone: Europe/Berlin
[ WARNING ]: 09:09:11 | Could not parse systemd-firstboot output
[ WARNING ]: 09:09:11 | chkstat not found in image. File Permissions Check skipped
[ INFO    ]: 09:09:11 | Calling config.sh script
[ INFO    ]: 09:09:11 | Using package manager backend: apt-get
[ INFO    ]: 09:09:11 | Cleaning up SystemPrepare instance
[ INFO    ]: 09:09:11 | Creating system image
[ INFO    ]: 09:09:11 | Preparing boot system
[ INFO    ]: 09:09:11 | Precalculating required disk size
[ INFO    ]: 09:09:12 | --> system data with filesystem overhead needs 1196 MB
[ INFO    ]: 09:09:12 | --> swap partition adding 128 MB
[ INFO    ]: 09:09:12 | --> legacy bios boot partition adding 2 MB
[ INFO    ]: 09:09:12 | --> EFI partition adding 20 MB
[ INFO    ]: 09:09:12 | Using calculated disk size: 1346 MB
[ INFO    ]: 09:09:12 | Creating raw disk image /var/cache/debian-buster/Debian-Buster_appliance.x86_64-10.4.raw
[ INFO    ]: 09:09:13 | --> creating EFI CSM(legacy bios) partition
[ INFO    ]: 09:09:15 | --> creating EFI partition
[ INFO    ]: 09:09:17 | --> creating SWAP partition
[ INFO    ]: 09:09:20 | --> creating root partition
[ INFO    ]: 09:09:22 | Creating EFI(fat16) filesystem on /dev/mapper/loop0p2
[ INFO    ]: 09:09:22 | Creating root(ext4) filesystem on /dev/mapper/loop0p4
[ INFO    ]: 09:09:22 | Creating config.partids in boot system
[ INFO    ]: 09:09:22 | Export modprobe configuration
[ INFO    ]: 09:09:22 | Creating image identifier: 0x1ab90add
[ INFO    ]: 09:09:22 | Creating generic system etc/fstab
[ INFO    ]: 09:09:22 | Creating generic dracut initrd archive
[ INFO    ]: 09:09:46 | --> initrd archive as initrd.img-4.19.0-14-amd64
[ INFO    ]: 09:09:46 | Creating grub2 bootloader configuration
[ INFO    ]: 09:09:46 | Creating grub2 bootloader images
[ INFO    ]: 09:09:47 | --> Creating unsigned efi image
[ INFO    ]: 09:09:47 | Writing grub2 defaults file
[ INFO    ]: 09:09:47 | --> GRUB_GFXMODE:auto
[ INFO    ]: 09:09:47 | --> GRUB_TERMINAL:"gfxterm"
[ INFO    ]: 09:09:47 | --> GRUB_THEME:/boot/grub/themes/starfield/theme.txt
[ INFO    ]: 09:09:47 | --> GRUB_TIMEOUT:10
[ INFO    ]: 09:09:47 | Writing sysconfig bootloader file
[ INFO    ]: 09:09:47 | --> DEFAULT_APPEND:"root=UUID=b92f5761-fadf-4e7d-a5c7-b8189f31cf6c rw "
[ INFO    ]: 09:09:47 | --> FAILSAFE_APPEND:"root=UUID=b92f5761-fadf-4e7d-a5c7-b8189f31cf6c rw  ide=nodma apm=off noresume edd=off nomodeset 3 "
[ INFO    ]: 09:09:47 | --> LOADER_LOCATION:none
[ INFO    ]: 09:09:47 | --> LOADER_TYPE:grub2-efi
[ INFO    ]: 09:09:47 | Creating config.bootoptions
[ INFO    ]: 09:09:47 | Syncing system to image
[ INFO    ]: 09:09:47 | --> Syncing EFI boot data to EFI partition
[ WARNING ]: 09:09:47 | Extended attributes not supported for target: /tmp/kiwi_mount_manager.stmt6bpi
[ INFO    ]: 09:09:47 | --> Syncing root filesystem data
[ INFO    ]: 09:09:50 | Copying /var/cache/debian-buster/build/image-root/boot/efi/EFI/BOOT/earlyboot.cfg -> /tmp/kiwi_mount_manager.r6jxn1dk/boot/efi/EFI/BOOT/grub.cfg to be found by EFI
[ INFO    ]: 09:09:50 | Cleaning up BootLoaderConfigGrub2 instance
[ INFO    ]: 09:09:50 | Installing grub2 on disk /dev/loop0
[ INFO    ]: 09:09:52 | Cleaning up BootLoaderInstallGrub2 instance
[ INFO    ]: 09:09:52 | Saving boot image instance to file
[ INFO    ]: 09:09:52 | Export deb packages metadata
[ INFO    ]: 09:09:52 | Export deb packages changelog metadata
[ INFO    ]: 09:09:54 | Export deb verification metadata
[ INFO    ]: 09:09:55 | Cleaning up FileSystemSwap instance
[ INFO    ]: 09:09:55 | Cleaning up FileSystemExt4 instance
[ INFO    ]: 09:09:55 | umount FileSystemExt4 instance
[ INFO    ]: 09:09:55 | Cleaning up FileSystemFat16 instance
[ INFO    ]: 09:09:55 | umount FileSystemFat16 instance
[ INFO    ]: 09:09:56 | Cleaning up Disk instance
[ INFO    ]: 09:09:56 | Cleaning up LoopDevice instance
[ INFO    ]: 09:09:56 | Creating hybrid ISO installation image
[ INFO    ]: 09:09:56 | Creating disk image checksum
[ INFO    ]: 09:09:59 | Creating squashfs embedded disk image
[ INFO    ]: 09:10:54 | Setting up install image bootloader configuration
[ INFO    ]: 09:10:54 | Creating grub2 bootloader images
[ INFO    ]: 09:10:54 | --> Creating identifier file 0x8c91fb4e
[ INFO    ]: 09:10:54 | --> Creating bios image
[ ERROR   ]: 09:10:54 | KiwiCommandError: chroot: stderr: grub-mkimage: error: cannot open `/usr/share/grub2/i386-pc/core.img': No such file or directory.
, stdout: (no output on stdout)
[ INFO    ]: 09:10:54 | Cleaning up FileSystemSquashFs instance
[ INFO    ]: 09:10:54 | Cleaning up BootLoaderConfigGrub2 instance
[ INFO    ]: 09:10:54 | Cleaning up InstallImageBuilder instance
```

**Comment by schaefi** [comment]
Oh I see our example image description is missing the pc modules. Please add the following to your image description

```xml
<package name="grub-pc-bin"/>
<package name="grub2-common"/>
```

That should fix it

We need to fix our example

**Comment by gdstewart** [comment]
I added those two packages but I am unfortunately still getting the same error.

**Comment by schaefi** [comment]
Hmm, interesting. Can you please double check your description with our Debian integration test from here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:debian/test-image-live-disk

It worked for me but maybe I overlooked something.

Thanks

**Comment by gdstewart** [comment]
@schaefi We were using `grub-efi-amd64` instead of `grub-efi-amd64-bin`, but after adjusting this I am still getting the error.

**Comment by schaefi** [comment]
Strange. Could you please run the build process with ```--debug``` and send us the complete log file. I need to see how grub mkimage was called in your case. I really wonder why it uses /usr/share/grub2. That's pretty wrong. On the debian build I send you the link you can see it looks like this:

```
[  554s] [ DEBUG   ]: 12:50:24 | EXEC: [chroot /usr/src/packages/KIWI-oem/build/
image-root grub-mkimage -O i386-pc -o /usr/lib/grub/i386-pc/core.img -c /boot/gr
ub/earlyboot.cfg -p /boot/grub -d /usr/lib/grub/i386-pc ext2 iso9660 linux echo 
configfile search_label search_fs_file search search_fs_uuid ls normal gzio png 
fat gettext font minicmd gfxterm gfxmenu all_video xfs btrfs lvm luks gcry_rijnd
ael gcry_sha256 gcry_sha512 crypto cryptodisk test true loadenv part_gpt part_ms
dos biosdisk vga vbe chain boot]
```

We need to see your log

Thanks

**Comment by jimfunk** [comment]
I can replicate this. I am running 9.23.20 from Virtualization:Appliances:Staging on Tumbleweed.

Attaching the log.

[kiwi-buster.log](https://github.com/OSInside/kiwi/files/6148903/kiwi-buster.log)

**Comment by schaefi** [comment]
Thanks for the log. I can see for the efi image it uses correctly:

```
EXEC: [chroot /var/cache/debian-buster/build/image-root grub-mkimage -O x86_64-efi -o /boot/efi/EFI/BOOT/bootx64.efi -c /boot/efi/EFI/BOOT/earlyboot.cfg -p /boot/grub -d /usr/lib/grub/x86_64-efi ...
```

and for the bios image it uses the wrong path

```
EXEC: [chroot /var/cache/debian-buster/build/image-root grub-mkimage -O i386-pc -o /usr/share/grub2/i386-pc/core.img -c /boot/grub/earlyboot.cfg -p /boot/grub -d /usr/share/grub2/i386-pc
```

Can you confirm there is no path:

* /var/cache/debian-buster/build/image-root/usr/share/grub2/i386-pc

But there should be this path:

* /var/cache/debian-buster/build/image-root/usr/lib/grub/i386-pc

which you should have in your image if the packages

* grub-pc-bin
* grub-pc

are installed. kiwi uses a default grub path if it can't find the modules by a search. That default path is not correct on Debian because grub is packaged differently. However kiwi finds this out if the packages providing the modules are actually installed.

Thus my original question still persists. Are you sure you are installing the pc modules into your image ?

According to our integration test this works:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:debian/test-image-live-disk

```
[chroot /usr/src/packages/KIWI-oem/build/image-root grub-mkimage -O i386-pc -o /usr/lib/grub/i386-pc/core.img -c /boot/grub/earlyboot.cfg -p /boot/grub -d /usr/lib/grub/i386-pc ...
```

The integration test runs with the repos from:

```
<repository type="apt-deb" distribution="buster" components="main contrib non-free" repository_gpgcheck="false">
    <source path="obs://Debian:10/universe"/>
</repository>
<repository type="apt-deb" distribution="buster" components="main contrib non-free" repository_gpgcheck="false">
    <source path="obs://Debian:10/standard"/>
</repository>
```

Let's check based on that what is different in your case

Thanks

**Comment by gdstewart** [comment]
I added `grub-pc` to our packages:
```
<package name="grub-efi-amd64-bin"/>
<package name="grub-pc"/>
<package name="grub-pc-bin"/>
<package name="grub2-common"/>
```
Here is the log on latest build: 

[2021-03-18.log](https://github.com/OSInside/kiwi/files/6167342/2021-03-18.log)

**Comment by jimfunk** [comment]
Confirming here with the kiwi-descriptions config with grub-pc-bin and grub2-common added.

Here are the installed grub packages:

```
jamesoakley:/home/jfunk/bi/kiwi-descriptions # chroot /var/cache/debian-buster/build/image-root/
root@jamesoakley:/# dpkg -l|grep grub
ii  grub-common                    2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader (common files)
ii  grub-efi-amd64                 2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (EFI-AMD64 version)
ii  grub-efi-amd64-bin             2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (EFI-AMD64 modules)
rc  grub-pc                        2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (PC/BIOS version)
ii  grub-pc-bin                    2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (PC/BIOS modules)
ii  grub-theme-starfield           2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (starfield theme)
rc  grub2                          2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader, version 2 (dummy package)
ii  grub2-common                   2.02+dfsg1-20+deb10u3               amd64        GRand Unified Bootloader (common files for version 2)
```

The `/var/cache/debian-buster/build/image-root/usr/share/grub2/i386-pc path does not exist` but `/var/cache/debian-buster/build/image-root/usr/lib/grub/i386-pc` does.

Log attached.

[kiwi-buster.log](https://github.com/OSInside/kiwi/files/6182527/kiwi-buster.log)

**Comment by jimfunk** [comment]
I did some more testing and it looks like this problem is exclusive to Tumbleweed.

I installed Leap 15.2 in an nspawn container and built from the same checkout of kiwi-descriptions with grub-pc-bin and grub2-common added. With the kiwi shipped in Leap 15.2, 9.21.23, it works fine. I also updated to 9.23.22 from Virtualization:Appliances:Staging and it worked as well. 

Attaching the log from the successful build on 15.2 with 9.3.22.

[kiwi-buster.log](https://github.com/OSInside/kiwi/files/6196785/kiwi-buster.log)

**Comment by schaefi** [comment]
Thanks much for all the details. As we are looking for the grub path inside of the image root, this part should not be depending on the host. Maybe there is an issue in the _get_efi_modules_path() method of kiwi but I don't see it at the moment. I think it would be in general a good idea to add some debug log information about the grub lookup done by kiwi. As a consequence of this report I'll prepare a PR to add at least this part. 

Maybe that helps to find the real cause

One final question. You are building Debian on Leap, from where did you fetched the Debian tooling (debootstrap/dpkg) ?

Thanks

YFI: Some Notes from past experience

* From my experience it is a good concept to build images on hosts that matches the image Distribution. For that purpose we provide the kiwi box plugin as documented here: https://osinside.github.io/kiwi/self_contained.html. Maybe this is useful to you too.

* You mentioned you build images in a ```nspawn container```. Please remember a container always shares the kernel with
the host and an image build process inside of the container has to run as root which requires the container to be privileged.
This opens a can of worms if the host system and the container system are not compatible on the level of e.g libdevmapper,
the kernel, loops and more. Therefore a real safe encapsulation of an image build process can only be achieved in a full
virtual environment like we provide with boxbuild using KVM.

**Comment by jimfunk** [comment]
The tooling is from Tumbleweed, eg: `zypper in dpkg debootstrap`

Thanks for the pointer to the kiwi box plugin. That looks worth trying. Ultimately I want it to simply build in our OBS instance, but that didn't work for me the last time I tried. I should take another stab at that.

**Comment by schaefi** [comment]
I'm going to add the extra information which grub path was actually used to be part of the log information and will close this issue then, as I think for now we will not be able to directly find the reason due to the TW target which constantly changes. If the issue persists let's revise it a later point in time. Hope this will work for you ? Thanks

**Comment by schaefi** [comment]
closing per merge of #1823
