### ISSUE TITLE
Can't build Debian 11, Ubuntu 22.04, Ubuntu 20.04 (realpath No such file or directory)

### ISSUE THREAD

**Issue by yaroslav-gwit** [OSInside/kiwi#2660]
## Problem description
Today I tried building/refreshing my older VM images (which built fine in the past), but the build process has ended unexpectedly with the following error:

Ubuntu 22.04 build logs
```log
[ DEBUG   ]: 17:53:55 | EXEC: [rm -f /root/OS_builds/gwit-ubuntu-20-04/build/image-root/etc/resolv.conf.kiwi /root/OS_builds/gwit-ubuntu-20-04/build/image-root/etc/resolv.conf.sha /root/OS_builds/gwit-ubuntu-20-04/build/image-root/etc/hosts.kiwi /root/OS_builds/gwit-ubuntu-20-04/build/image-root/etc/hosts.sha]
[ ERROR   ]: 17:53:55 | KiwiDebianBootstrapError: KiwiCommandError: apt-get: stderr: W: GPG error: http://gb.archive.ubuntu.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
E: flAbsPath on /var/lib/dpkg/status.kiwi failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.
, stdout: Get:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages [970 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu focal/main Translation-en [506 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]
Get:5 http://gb.archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]
Get:6 http://gb.archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [22.0 kB]
Get:7 http://gb.archive.ubuntu.com/ubuntu focal/restricted Translation-en [6212 B]
Get:8 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]
Get:9 http://gb.archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
Fetched 15.8 MB in 3s (5305 kB/s)
Reading package lists..
```

Debian 11 build logs
```log
[ DEBUG   ]: 17:53:51 | EXEC: [apt-get -q -c /root/OS_builds/gwit-ubuntu-20-04/build/image-root/kiwi_apt.conf -y --no-install-recommends update]
[ DEBUG   ]: 17:53:55 | EXEC: Failed with stderr: W: GPG error: http://gb.archive.ubuntu.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
E: flAbsPath on /var/lib/dpkg/status.kiwi failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.
, stdout: Get:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages [970 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu focal/main Translation-en [506 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]
Get:5 http://gb.archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]
Get:6 http://gb.archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [22.0 kB]
Get:7 http://gb.archive.ubuntu.com/ubuntu focal/restricted Translation-en [6212 B]
Get:8 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]
Get:9 http://gb.archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
Fetched 15.8 MB in 3s (5305 kB/s)
Reading package lists...
```

## Expected behaviour
Image build process should end with a success. The fun fact, is that I am able to build `debian12` and `ubuntu24.04`, but not the older releases.

I tried building under 3 different systems: `AlmaLinux8`, `Debian11` and `Debian12`, all with the same outcome.
I've also applied the fix described here, but it didn't help:
```link
https://github.com/OSInside/kiwi/issues/2193#issuecomment-1280771269
```

## OS and Software information
* KIWI version: `KIWI (next generation) version 10.1.13`
* Operating system target version: `debian11`, `ubuntu20.04`, `ubuntu22.04`.
* Open Build Service version (N/A if not using OBS):  N/A
* Koji version (N/A if not using Koji): N/A

**Comment by schaefi** [comment]
We are discussing this... stay tuned. It will be aligned with the current PR #2659

**Comment by yaroslav-gwit** [comment]
Thank you very much for the heads-up. I'll wait for the patch then :sweat_smile:

**Comment by yaroslav-gwit** [comment]
Build still fails, unfortunately. Has the patch been pushed to the upstream (aka `https://pypi.org/project/kiwi/`) yet? If not, which version should I roll back to, in order to get the build process working?

**Comment by schaefi** [comment]
@yaroslav-gwit sorry late response, we were all out on a workshop in Portland

The changes were pushed out to pypi for version 10.1.14, this version should have fixed the issue. If not can you please provide a full build log from an attempt with 10.1.14 ? Thanks

**Comment by yaroslav-gwit** [comment]
Looks like the issue is still there:
```
...some more output
[ INFO    ]: 20:56:10 | --> package: usrmerge
[ INFO    ]: 20:56:10 | --> package: vim
[ INFO    ]: 20:56:10 | --> package: wget
[ INFO    ]: 20:56:10 | --> package: xz-utils
[ DEBUG   ]: 20:56:10 | Looking for chroot in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/gwitsuper/.local/bin
[ DEBUG   ]: 20:56:10 | EXEC: [chroot /root/OS_builds/gwit-debian-11/build/image-root apt-get -q -c /kiwi_apt.conf -y --no-install-recommends update]
[ DEBUG   ]: 20:56:10 | EXEC: Failed with stderr: W: No sandbox user '_apt' on the system, can not drop privileges
W: GPG error: http://ftp.de.debian.org/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY 605C66F00D6C9793
E: flAbsPath on /var/lib/dpkg/status.kiwi failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.
, stdout: Get:1 http://ftp.de.debian.org/debian bullseye InRelease [116 kB]
Ign:1 http://ftp.de.debian.org/debian bullseye InRelease
Fetched 116 kB in 0s (613 kB/s)
Reading package lists...

...some more debug output
[ DEBUG   ]: 20:56:10 | EXEC: [rm -f /root/OS_builds/gwit-debian-11/build/image-root/etc/hosts]
[ DEBUG   ]: 20:56:10 | Looking for rm in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/gwitsuper/.local/bin
[ DEBUG   ]: 20:56:10 | EXEC: [rm -f /root/OS_builds/gwit-debian-11/build/image-root/etc/resolv.conf.kiwi /root/OS_builds/gwit-debian-11/build/image-root/etc/resolv.conf.sha /root/OS_builds/gwit-debian-11/build/image-root/etc/hosts.kiwi /root/OS_builds/gwit-debian-11/build/image-root/etc/hosts.sha]
[ ERROR   ]: 20:56:10 | KiwiCommandError: chroot: stderr: W: No sandbox user '_apt' on the system, can not drop privileges
W: GPG error: http://ftp.de.debian.org/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY 605C66F00D6C9793
E: flAbsPath on /var/lib/dpkg/status.kiwi failed - realpath (2: No such file or directory)
E: Could not open file  - open (2: No such file or directory)
E: Problem opening 
E: The package lists or status file could not be parsed or opened.
, stdout: Get:1 http://ftp.de.debian.org/debian bullseye InRelease [116 kB]
Ign:1 http://ftp.de.debian.org/debian bullseye InRelease
Fetched 116 kB in 0s (613 kB/s)
Reading package lists...

**Comment by schaefi** [comment]
>Looks like the issue is still there (but it's a different one this time):

@yaroslav-gwit yeah it took me a while to find out why the scripts cannot run. I will come up with another PR to address this part

**Comment by schaefi** [comment]
The patch that should fix it was merged but I reopen this one to track if it's really solved for @yaroslav-gwit

**Comment by schaefi** [comment]
@yaroslav-gwit I have not yet created a new release. So for testing you would need to patch your kiwi locally or wait until I create a new release

**Comment by yaroslav-gwit** [comment]
Is the patch in `main` already? I tried building the package from `main` today, but then the OS image build still failed with the same error. Maybe the missing keys have something to do with it?
```
Reading package lists...
 W: GPG error: http://ftp.de.debian.org/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY 605C66F00D6C9793
```

**Comment by schaefi** [comment]
@yaroslav-gwit I taged v10.1.15 and it should appear in pypi for your testing.

**Comment by schaefi** [comment]
@yaroslav-gwit great :) happy we could sort this out and thanks for the feedback
